site_name: Rush Analytics API Documentation
theme:
  name: material
plugins:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_style: google
nav:
  - Home: index.md
  - API Reference:
      - Endpoints: endpoints.md
